stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.informatics.ru/2024-2025/korolev/s103/final-project-kalinin-team
  DOCKER_TAG: latest

unit_tests:
  stage: test
  image: python:3.13-slim
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test

build_docker:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  rules:
    - if: $CI_COMMIT_BRANCH == "stable"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy_prod:
  stage: deploy
  image: alpine:3.18
  rules:
    - if: $CI_COMMIT_BRANCH == "stable"
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no user@$SERVER_IP "cd /path/to/project && docker-compose pull && docker-compose down && docker-compose up -d"