services:
  - type: web
    name: mappu
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: gunicorn WireMap.wsgi:application --bind 0.0.0.0:$PORT --log-level debug
    releaseCommand: "python manage.py migrate"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: postgres://myuser:zyaKnE3WImuhsoElFThfN8asiArepbPc@dpg-d0aghdh5pdvs73ecld00-a:5432/mydb_e5kg
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: RENDER
        value: "true"

# Используем существующую базу данных, не создаем новую
# databases:
#   - name: my-django-db
#     databaseName: mydb_e5kg
#     plan: free 