services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt && DJANGO_SETTINGS_MODULE=WireMap.settings python manage.py collectstatic --noinput
    startCommand: gunicorn WireMap.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: postgresql://myuser:zyaKnE3WImuhsoElFThfN8asiArepbPc@dpg-d0aghdh5pdvs73ecld00-a/mydb_e5kg
      - key: DB_PASSWORD
        value: zyaKnE3WImuhsoElFThfN8asiArepbPc
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: STATIC_ROOT
        value: /app/MainApp/staticfiles

# Используем существующую базу данных, не создаем новую
# databases:
#   - name: my-django-db
#     databaseName: mydb_e5kg
#     plan: free 