databases:
  - name: mappu-db
    plan: free
    databaseName: mappu
    user: mappu

services:
  - type: web
    name: mappu
    env: python
    buildCommand: "./build.sh"  # Используем наш скрипт сборки
    startCommand: python -m gunicorn WireMap.wsgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: mappu-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: STATIC_ROOT
        value: /var/task/staticfiles
      - key: WEB_CONCURRENCY
        value: "4"

# Используем существующую базу данных, не создаем новую
# databases:
#   - name: my-django-db
#     databaseName: mydb_e5kg
#     plan: free 