services:
  - type: web
    name: mappu
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: gunicorn WireMap.wsgi:application --bind 0.0.0.0:$PORT --log-level debug
    releaseCommand: "python manage.py migrate"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: RENDER
        value: "true"
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}

# Используем существующую базу данных, не создаем новую
# databases:
#   - name: my-django-db
#     databaseName: mydb_e5kg
#     plan: free 