services:
  - type: web
    name: wiremap
    env: python
    buildCommand: pip install -r requirements.txt && DJANGO_SETTINGS_MODULE=WireMap.settings python manage.py collectstatic --noinput
    startCommand: gunicorn WireMap.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: STATIC_ROOT
        value: /app/MainApp/staticfiles

databases:
  - name: postgres
    databaseName: wiremap
    plan: free 