services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: >
      pip install -r requirements.txt && 
      mkdir -p media/profile_pics &&
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations MainApp --noinput &&
      python manage.py migrate auth --noinput &&
      python manage.py migrate --run-syncdb &&
      python -c "
      import os
      os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'WireMap.settings')
      import django
      django.setup()
      from django.contrib.auth import get_user_model
      User = get_user_model()
      if not User.objects.filter(username='admin').exists():
          User.objects.create_superuser('admin', 'admin@example.com', 'adminpassword')
          print('Superuser created.')
      else:
          print('Superuser already exists.')
      "
    startCommand: gunicorn WireMap.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "true"
      - key: STATIC_ROOT
        value: /app/MainApp/staticfiles

# Используем существующую базу данных, не создаем новую
# databases:
#   - name: my-django-db
#     databaseName: mydb_e5kg
#     plan: free 