databases:
  - name: my-django-db
    plan: free
    databaseName: mydb_e5kg
    user: myuser
    password: zyaKnE3WImuhsoElFThfN8asiArepbPc

services:
  - type: web
    name: mappu
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: gunicorn WireMap.wsgi:application --bind 0.0.0.0:$PORT --log-level debug
    releaseCommand: "python manage.py migrate"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: my-django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: POSTGRES_USER
        value: myuser
      - key: POSTGRES_DB
        value: mydb_e5kg
      - key: RENDER
        value: "true"
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false

# Используем существующую базу данных, не создаем новую
# databases:
#   - name: my-django-db
#     databaseName: mydb_e5kg
#     plan: free 