databases:
  - name: mappu-db
    plan: free
    databaseName: mappu
    user: mappu

services:
  - type: web
    name: mappu
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: gunicorn WireMap.wsgi:application --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      # Переменная окружения для подключения к базе данных будет настроена 
      # автоматически Render после создания базы данных
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: STATIC_ROOT
        value: /var/task/staticfiles
      - key: WEB_CONCURRENCY
        value: "4"
      - key: INIT_DB
        value: "true"

# Используем существующую базу данных, не создаем новую
# databases:
#   - name: my-django-db
#     databaseName: mydb_e5kg
#     plan: free 