# Generated by Django 5.2 on 2025-04-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='temp_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='temp_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
