# Generated by Django 5.2 on 2025-05-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(help_text='Массив координат [[lon, lat], [lon, lat], ...] для линии ветки.')),
                ('description', models.TextField(blank=True, help_text='Описание ветки.', null=True)),
                ('temp_id', models.IntegerField(blank=True, db_index=True, help_text='Временный ID для операций на фронтенде.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(help_text='Карта, к которой принадлежит эта ветка.', on_delete=django.db.models.deletion.CASCADE, related_name='branches_on_map', to='MainApp.map')),
                ('parent_branch', models.ForeignKey(blank=True, help_text='Родительская ветка, от которой отходит эта ветка (если не от Edge).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_branches', to='MainApp.branch')),
                ('source_edge', models.ForeignKey(blank=True, help_text='Основное ребро (Edge), от которого отходит эта ветка (если не от другой ветки).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches_from_edge', to='MainApp.edge')),
                ('terminal_node', models.ForeignKey(blank=True, help_text='Узел (Node), в котором заканчивается эта ветка, если она является листом.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminating_branches', to='MainApp.node')),
            ],
            options={
                'verbose_name': 'Ветка',
                'verbose_name_plural': 'Ветки',
                'ordering': ['created_at'],
            },
        ),
    ]
