# Generated by Django 5.2 on 2025-04-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
