# Generated by Django 4.2.17 on 2025-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
