# Generated by Django 5.2 on 2025-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_map_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Хештег',
                'verbose_name_plural': 'Хештеги',
            },
        ),
        migrations.AddField(
            model_name='map',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='maps', to='MainApp.hashtag'),
        ),
    ]
