# Generated by Django 5.2 on 2025-05-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_map_map_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='map_settings',
        ),
    ]
