# Generated by Django 5.2 on 2025-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='IMAGES/avatar.png', null=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
