# Generated by Django 5.1.6 on 2025-02-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('edges', models.ManyToManyField(related_name='maps', to='MainApp.edge')),
                ('nodes', models.ManyToManyField(related_name='maps', to='MainApp.node')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='node1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='MainApp.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='node2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='MainApp.node'),
        ),
    ]
