# Generated by Django 5.1.6 on 2025-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='z_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
