# Generated by Django 5.1.7 on 2025-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_edge_description_node_description_node_z_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='center_latitude',
            field=models.FloatField(default=55.921708),
        ),
        migrations.AddField(
            model_name='map',
            name='center_longitude',
            field=models.FloatField(default=37.814387),
        ),
    ]
