# Generated by Django 5.1.7 on 2025-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_map_center_latitude_map_center_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
