# Generated by Django 5.2 on 2025-05-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
