# Generated by Django 5.1.6 on 2025-03-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_map_owner_alter_map_center_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='node1',
            new_name='start_node',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='node2',
            new_name='end_node',
        ),
    ] 